using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using StockManagement.Domain.Entities;
using StockManagement.Infrastructure.Repositories;

namespace StockManagement.Application.Services;

public class ReportService
{
    private readonly ReconciliationService _recon;
    private readonly ReportRepository _reportRepo;

    public ReportService(ReconciliationService recon, ReportRepository reportRepo)
    {
        _recon = recon;
        _reportRepo = reportRepo;
    }

    public async Task<ReportRecord> GenerateAndStoreEodAsync(string branchId, DateTime date, string generatedBy)
    {
        var balances = await _recon.CalculateEodAsync(branchId, date);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"EOD Report - {date:yyyy-MM-dd}");
        sb.AppendLine($"Branch: {branchId}");
        sb.AppendLine($"Generated by: {generatedBy} on {DateTime.UtcNow:yyyy-MM-dd HH:mm}");
        sb.AppendLine(new string('-', 40));
        foreach (var b in balances)
        {
            sb.AppendLine($"{b.Type}: Opening={b.Opening} Receipts={b.Receipts} Issued={b.Issued} Destroyed={b.Destroyed} Closing={b.Closing}");
        }

        var bytes = System.Text.Encoding.UTF8.GetBytes(sb.ToString());

        var rec = await _reportRepo.SaveReportAsync(branchId, date, generatedBy, bytes);
        return rec;
    }

    public Task AddSignOffAsync(Guid reportId, string authoriserId, string comments)
    {
        var sign = new ReportSignOff
        {
            ReportRecordId = reportId,
            AuthoriserId = authoriserId,
            SignedAt = DateTime.UtcNow,
            Comments = comments
        };

        return _reportRepo.AddSignOffAsync(sign);
    }
}
